apps:
  pages:
  - number: 1
    items:
    - iTerm
    - folder: ☕ code
      pages:
      - number: 1
        items:
        - Sublime Text
        - WebStorm
        - PhpStorm
        - Visual Studio Code
        - Postman
        - Integrity
        - Kitematic
        - Xcode
        - Docker
        - Tower
    - folder: "\U0001F3B2 db"
      pages:
      - number: 1
        items:
        - Sequel Pro
        - MySQLWorkbench
        - Postico
        - DbVisualizer
        - DB Browser for SQLite
        - NoSQLBooster for MongoDB
        - Robo 3T
        - MongoHub
        - DBeaver
    - folder: "\U0001F4BC office"
      pages:
      - number: 1
        items:
        - Pages
        - Marp
        - Kap
        - Numi
        - Gisto
    - folder: "\U0001F4AC social"
      pages:
      - number: 1
        items:
        - Telegram
        - FaceTime
        - Discord
        - Volt
        - Conferences
        - Rocket.Chat
        - Spectrum
    - folder: "\U0001F4BE volumes"
      pages:
      - number: 1
        items:
        - Utilitário de Disco
        - SD Card Formatter
        - balenaEtcher
        - Disk Inventory X
    - folder: ☠ system
      pages:
      - number: 1
        items:
        - App Store
        - CCleaner
        - OnyX
        - Macs Fan Control
        - Utilitário AirPort
        - iStumbler
        - dupeGuru
    - folder: "\U0001F511 security"
      pages:
      - number: 1
        items:
        - Keybase
        - GPG Keychain
        - QtPass
        - Cryptomator
        - Acesso às Chaves
        - MacPass
    - Preferências do Sistema
    - Typora
  - number: 2
    items:
    - folder: "\U0001F517 web"
      pages:
      - number: 1
        items:
        - Brave Browser
        - Firefox
        - Safari
        - ParseHub
        - Opera
        - Tor Browser
        - SRWare Iron
    - folder: "\U0001F3AC media"
      pages:
      - number: 1
        items:
        - VLC
        - QuickTime Player
        - IINA
        - mpv
        - Stremio
    - Fotos
    - GreenAddress Wallet
    - folder: 
      pages:
      - number: 1
        items:
        - Automator
        - Terminal
        - Monitor de Atividade
        - Console
        - Informações do Sistema
        - Editor de Scripts
        - Catálogo de Fontes
        - Notas
        - Calendário
        - iTunes
        - Contatos
      - number: 2
        items:
        - Siri
        - Assistente do Boot Camp
        - Utilitário do VoiceOver
        - Captura
        - Configuração de Áudio e MIDI
        - Assistente de Migração
        - Time Machine
        - Pré-Visualização
        - Intercâmbio de Arquivos Bluetooth
        - Grapher
        - Utilitário ColorSync
        - Medidor de Cor Digital
        - Captura de Imagem
    - folder: "\U0001F5D1"
      pages:
      - number: 1
        items:
        - Amethyst
        - Spectacle
        - Keka
        - Keyboard Maestro
        - Transmit Disk
        - Karabiner-Elements
        - Karabiner-EventViewer
        - Turbo Download Manager
        - Flux
        - DiffMerge
    - Transmission
    - JDownloader2
    - VNC Viewer
    - 0 A.D
    - Calculadora
widgets:
  pages:
  - number: 1
    items:
    - Anotações
    - Bolsa
    - Calculadora
    - Calendário
    - Contatos
    - Conversor
    - Dicionário
    - Jogo de Peças
    - Movies
    - Previsão do Tempo
    - Relógio
    - Web Clip
dock_items:
- SRWare Iron
- ============
- Transferências
desktop: {}
